apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "billing-relay.fullname" . }}-configmap
data:
  {{- range $key, $val := .Values.config }}
  {{- if kindIs "bool" $val }}
  {{ $key }}: {{ tpl ($val | quote) $ }}
  {{- else }}
  {{ $key }}: {{ tpl $val $ }}
  {{- end }}
  {{- end }}
