---
name: _docker
run-name: "Build docker image - ${{ inputs.project-name }} - Push to ACR: ${{ inputs.push-docker-image }}"

on:
  workflow_call:
    inputs:
      project-name:
        type: string
        required: true
      project-path:
        type: string
        required: true
      version:
        type: string
        required: false
      push-docker-image:
        type: boolean
        required: false
        default: false

jobs:
  build:
    name: Build ${{ inputs.project-name }}
    runs-on: ubuntu-22.04
    steps:

      - name: Login to Azure - PROD Subscription
        uses: Azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2 # v1.4.7
        with:
          creds: ${{ secrets.AZURE_PROD_KV_CREDENTIALS }}

      - name: Login to PROD ACR
        run: az acr login -n bitwardenprod

      ########## Generate image tag and build Docker image ##########
      - name: Generate Docker image tag
        id: tag
        env:
          VERSION: ${{ inputs.version }}
        run: |
          IMAGE_TAG=$(echo "${GITHUB_REF:11}" | sed "s#/#-#g")  # slash safe branch name
          if [[ "$IMAGE_TAG" == "main" ]]; then
            IMAGE_TAG=$VERSION
          fi
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Generate tag list
        id: tag-list
        env:
          IMAGE_TAG: ${{ steps.tag.outputs.image_tag }}
          PROJECT_NAME: ${{ inputs.project_name }}
        run: echo "tags=bitwardenprod.azurecr.io/${PROJECT_NAME}:${IMAGE_TAG}" >> $GITHUB_OUTPUT

      - name: Get build artifact
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: ${{ matrix.project_name }}.zip

      - name: Setup build artifact
        run: |
          mkdir -p ${{ inputs.project-path }}/${{ inputs.project-name }}/obj/build-output/publish
          unzip ${{ matrix.project_name }}.zip \
            -d ${{ inputs.project-path }}/${{ inputs.project-name }}/obj/build-output/publish

      - name: Build Docker image
        uses: docker/build-push-action@1104d471370f9806843c095c1db02b5a90c5f8b6 # v3.3.1
        with:
          context: ${{ inputs.project-path }}/${{ inputs.project-name }}
          file: ${{ inputs.project-path }}/${{ inputs.project-name }}/Dockerfile
          platforms: linux/amd64
          push: ${{ inputs.push-docker-image }}
          tags: ${{ steps.tag-list.outputs.tags }}