---
name: _docker
run-name: "Build ${{ inputs.project-name }} docker image and push ${{ inputs.push-docker-image }} to ACR"

on:
  workflow_call:
    inputs:
      project-name:
        type: string
        required: true
      project-path:
        type: string
        required: true
      version:
        type: string
        required: false
      push-docker-image:
        type: boolean
        required: false
        default: false
      image-name:
        type: string
        required: true

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: Log in to Azure
        if: ${{ inputs.push-docker-image }}
        uses: Azure/login@e15b166166a8746d1a47596803bd8c1b595455cf # v1.6.0
        with:
          creds: ${{ secrets.AZURE_PROD_KV_CREDENTIALS }}

      - name: Log in to ACR
        if: ${{ inputs.push-docker-image }}
        run: az acr login -n bitwardenprod

      - name: Generate Docker image tag
        id: tag
        env:
          VERSION: ${{ inputs.version }}
        run: |
          IMAGE_TAG=$VERSION
          # IMAGE_TAG=$(echo "${GITHUB_REF#refs/heads/}" | sed "s#/#-#g")  # slash safe branch name
          # if [[ "$IMAGE_TAG" == "main" ]]; then
          #   IMAGE_TAG=$VERSION
          # fi
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Generate tag list
        id: tag-list
        env:
          IMAGE_TAG: ${{ steps.tag.outputs.image_tag }}
          IMAGE_NAME: ${{ inputs.image-name }}
        run: echo "tags=bitwardenprod.azurecr.io/${IMAGE_NAME}:${IMAGE_TAG}" >> $GITHUB_OUTPUT

      - name: Get build artifact
        uses: actions/download-artifact@eaceaf801fd36c7dee90939fad912460b18a1ffe # v4.1.2
        with:
          name: ${{ inputs.project-name }}.zip

      - name: Set up build artifact
        run: |
          mkdir -p ${{ inputs.project-path }}/obj/build-output/publish
          unzip ${{ inputs.project-name }}.zip \
            -d ${{ inputs.project-path }}/obj/build-output/publish

      - name: Build Docker image
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
        with:
          context: ${{ inputs.project-path }}
          file: ${{ inputs.project-path }}/Dockerfile
          platforms: linux/amd64
          push: ${{ inputs.push-docker-image }}
          tags: ${{ steps.tag-list.outputs.tags }}
