---
name: _release
run-name: Release ${{ inputs.version }}

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
    outputs:
      git-tag:
        description: The Git tag that was created using the version number.
        value: ${{ jobs.release.outputs.git-tag }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    env:
      _BOT_EMAIL: 106330231+bitwarden-devops-bot@users.noreply.github.com
      _BOT_NAME: bitwarden-devops-bot
    outputs:
      git-tag: ${{ steps.git-tag.outputs.tag }}
      git-tag-ref: ${{ steps.git-tag.outputs.tag_ref }}
    steps:
      - name: Check out repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: Create Git Tag
        id: git-tag
        run: |
          git config --local user.email "${{ env._BOT_EMAIL }}"
          git config --local user.name "${{ env._BOT_NAME }}"

          # Check if tag exists, set output then exit 0 if true.
          if git log v${{ inputs.version }} >/dev/null 2>&1; then
            echo "tag=v${{ inputs.version }}" >> $GITHUB_OUTPUT
            exit 0
          fi

          git tag v${{ inputs.version }}
          git push origin v${{ inputs.version }}

          echo "tag=v${{ inputs.version }}" >> $GITHUB_OUTPUT
          echo "tag_ref=$(git rev-list -n 1 tags/v${{ inputs.version }})" >> $GITHUB_OUTPUT
