name: _test
run-name: Test ${{ inputs.project-name }}

on:
  workflow_call:
    inputs:
      project-name:
        type: string
        required: true
      project-path:
        type: string
        required: true

jobs:
  testing:
    name: Test
    runs-on: ubuntu-22.04
    permissions:
      checks: write
      contents: read
      pull-requests: write
    env:
      _PROJECT_PATH: ${{ inputs.project-path }}
      _PROJECT_NAME: ${{ inputs.project-name }}

    steps:
      - name: Check out repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up .NET
        uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d # v5.0.0

      - name: Cache NuGet packages
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Install dependencies
        run: dotnet restore --locked-mode "$_PROJECT_PATH/$_PROJECT_NAME.csproj"

      - name: Build
        run: dotnet build --verbosity minimal "$_PROJECT_PATH/$_PROJECT_NAME.csproj"

      - name: Test
        run: dotnet test "$_PROJECT_PATH/$_PROJECT_NAME.csproj" --no-build --logger "trx;LogFileName=test-results.trx"

      - name: Report test results
        uses: dorny/test-reporter@dc3a92680fcc15842eef52e8c4606ea7ce6bd3f3 # v2.1.1
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository && !cancelled() }}
        with:
          name: Test Results
          path: "**/test-results.trx"
          reporter: dotnet-trx
          fail-on-error: true

      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@1e68e06f1dbfde0e4cefc87efeba9e4643565303 # v5.1.2
