name: _version
run-name: Calculate version

on:
  workflow_call:
    inputs:
      is-release:
        type: boolean
        default: false
    outputs:
      version:
        description: "version to be built"
        value: ${{ jobs.version.outputs.version }}

permissions:
  contents: read

jobs:
  version:
    name: Calculate version
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.version.outputs.value }}
    steps:
      - name: Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Generate version
        id: version
        env:
          IS_RELEASE: ${{ inputs.is-release }}
          COMMIT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
        run: |
          ls -la
          git fetch --prune --tags

          echo "Calculating next version..."

          base_version=$(
            grep -o "<BaseVersion>.*</BaseVersion>" Directory.Build.props |
            grep -Eo "[0-9]+\.[0-9]+"
          )
          major_version=$(echo "$base_version" | grep -Eo "[0-9]+" | head -1)
          minor_version=$(echo "$base_version" | grep -Eo "[0-9]+" | sed -n 2p)

          latest_tag_version=$(git tag --sort=committerdate --list | tail -1)
          echo "  latest_tag_version: $latest_tag_version"

          major_latest_tag_version=$(echo "$latest_tag_version" | grep -Eo "[0-9]+" | head -1)
          echo "  major_latest_tag_version: $major_latest_tag_version"

          minor_latest_tag_version=$(echo "$latest_tag_version" | grep -Eo "[0-9]+" | sed -n 2p)
          echo "  minor_latest_tag_version: $minor_latest_tag_version"

          if [[ "$major_latest_tag_version" != "$major_version" ]] || \
          [[ "$minor_latest_tag_version" != "$minor_version" ]]; then
            patch_version="0"
          else
            patch_version=$((${latest_tag_version##*.} + 1))
          fi

          echo "  patch_version: $patch_version"

          version_suffix="$patch_version"

          if [[ "$IS_RELEASE" == "false" ]]; then
            version_suffix="$version_suffix-${COMMIT_SHA:0:7}"
          fi

          echo "  version: $base_version.$version_suffix"
          echo "value=$base_version.$version_suffix" >> "$GITHUB_OUTPUT"
          echo "Done"
