name: _version
run-name: Calculate version

on:
  workflow_call:
    inputs:
      is-release:
        type: boolean
        default: false
    outputs:
      version:
        description: "version to be built"
        value: ${{ jobs.version.outputs.version }}

permissions:
  contents: read

jobs:
  version:
    name: Calculate version
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.version.outputs.value }}
    steps:
      - name: Check out repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Generate version
        id: version
        run: |
          ls -la
          git fetch --prune --tags

          echo "Calculating next version..."

          base_version=$(
            grep -o "<BaseVersion>.*</BaseVersion>" Directory.build.props |
            grep -Eo "[0-9]+\.[0-9]+"
          )
          major_version=$(echo $base_version | grep -Eo "[0-9]+" | head -1)
          minor_version=$(echo $base_version | grep -Eo "[0-9]+" | sed -n 2p)

          latest_tag_version=$(git tag --sort=committerdate --list | tail -1)
          echo "  latest_tag_version: $latest_tag_version"

          major_latest_tag_version=$(echo $latest_tag_version | grep -Eo "[0-9]+" | head -1)
          echo "  major_latest_tag_version: $major_latest_tag_version"

          minor_latest_tag_version=$(echo $latest_tag_version | grep -Eo "[0-9]+" | sed -n 2p)
          echo "  minor_latest_tag_version: $minor_latest_tag_version"

          if [[ "$major_latest_tag_version" != "$major_version" ]] || \
          [[ "$minor_latest_tag_version" != "$minor_version" ]]; then
            patch_version="0"
          else
            patch_version=$((${latest_tag_version##*.} + 1))
          fi

          echo "  patch_version: $patch_version"

          version_suffix=$patch_version

          if [[ "${{ inputs.is-release }}" == "false" ]]; then
            commit_sha=${{ github.event.pull_request.head.sha || github.sha }}
            version_suffix=$version_suffix-${commit_sha:0:7}
          fi

          echo "  version: $base_version.$version_suffix"
          echo "value=$base_version.$version_suffix" >> $GITHUB_OUTPUT
          echo "Done"
