name: CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "charts/**"

permissions: {}

jobs:
  version:
    name: Calculate version
    uses: ./.github/workflows/_version.yml
    permissions:
      contents: read
    with:
      is-release: true

  tag:
    name: Create release tag
    needs: version
    uses: ./.github/workflows/_create-release-tag.yml
    permissions:
      contents: write
    with:
      version: ${{ needs.version.outputs.version }}

  test:
    name: Run test
    uses: ./.github/workflows/_test.yml
    permissions:
      checks: write
      contents: read
      pull-requests: write
    with:
      project-name: Billing.Test
      project-path: ./test/Billing.Test

  build:
    name: Run build
    needs:
      - test
      - version
    uses: ./.github/workflows/_build.yml
    permissions:
      contents: read
    with:
      project-name: Billing
      project-path: ./src/Billing
      version: ${{ needs.version.outputs.version }}

  build-push-docker:
    name: Build and push Docker image
    needs:
      - test
      - version
      - build
    uses: ./.github/workflows/_docker.yml
    permissions:
      contents: read
      security-events: write
      id-token: write
    with:
      project-name: Billing
      project-path: ./src/Billing
      version: ${{ needs.version.outputs.version }}
      image-name: billing-relay
      push-docker-image: true
    secrets: inherit

  deploy:
    name: Trigger deployment via deploy repo
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
    needs:
      - tag
      - build-push-docker

    steps:
      - name: Trigger deployment
        uses: bitwarden/gh-actions/trigger-actions@main
        with:
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          task: deploy-billing-relay
          data: '{"tag": "${{ needs.tag.outputs.git-tag }}"}'
