name: Load test

on:
  schedule:
    - cron: "0 0 * * 1" # Run every Monday at 00:00
  workflow_dispatch:
    inputs:
      test-id:
        type: string
        description: "Identifier label for Datadog metrics"
        default: "billing-relay-load-test"
      k6-test-path:
        type: string
        description: "Path to load test files"
        default: "test/load/*.js"
      k6-flags:
        type: string
        description: "Additional k6 flags"
      # Test specific inputs
      billing-relay-env-url:
        type: string
        description: "URL of the billing relay environment"
        default: "https://billingrelay.qa.bitwarden.pw"

permissions:
  contents: read
  id-token: write

env:
  # Secret configuration
  AZURE_KEY_VAULT_NAME: gh-billing-relay
  AZURE_KEY_VAULT_SECRETS: billing-paypal-webhook-key,dd-api-key

  # Specify defaults for scheduled runs
  TEST_ID: ${{ inputs.test-id || 'billing-relay-load-test' }}
  K6_TEST_PATH: ${{ inputs.k6-test-path || 'test/load/*.js' }}
  BILLING_RELAY_ENV_URL: ${{ inputs.billing-relay-env-url || 'https://billingrelay.qa.bitwarden.pw' }}

jobs:
  run-tests:
    name: Run load tests
    runs-on: ubuntu-24.04
    steps:
      - name: Log in to Azure
        uses: bitwarden/gh-actions/azure-login@main
        with:
          subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          client_id: ${{ secrets.AZURE_CLIENT_ID }}

      - name: Get Azure Key Vault secrets
        id: get-kv-secrets
        uses: bitwarden/gh-actions/get-keyvault-secrets@main
        with:
          keyvault: ${{ env.AZURE_KEY_VAULT_NAME }}
          secrets: "${{ env.AZURE_KEY_VAULT_SECRETS }}"

      - name: Log out of Azure
        uses: bitwarden/gh-actions/azure-logout@main

      # Datadog agent for collecting OTEL metrics from k6
      - name: Start Datadog agent
        env:
          _DD_API_KEY: ${{ steps.get-kv-secrets.outputs.dd-api-key }}
        run: |
          docker run --detach \
            --name datadog-agent \
            -p 4317:4317 \
            -p 5555:5555 \
            -e DD_SITE=us3.datadoghq.com \
            -e DD_API_KEY="$_DD_API_KEY" \
            -e DD_DOGSTATSD_NON_LOCAL_TRAFFIC=1 \
            -e DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENDPOINT=0.0.0.0:4317 \
            -e DD_HEALTH_PORT=5555 \
            -e HOST_PROC=/proc \
            --volume /var/run/docker.sock:/var/run/docker.sock:ro \
            --volume /sys/fs/cgroup/:/host/sys/fs/cgroup:ro \
            --health-cmd "curl -f http://localhost:5555/health || exit 1" \
            --health-interval 10s \
            --health-timeout 5s \
            --health-retries 10 \
            --health-start-period 30s \
            --pid host \
            datadog/agent:7-full@sha256:800dfd060650a6eb147dd5697288dab1968e0bb0577785c59ca664f422c9299a

      - name: Check out repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Set up k6
        uses: grafana/setup-k6-action@ffe7d7290dfa715e48c2ccc924d068444c94bde2 # v1.1.0

      - name: Run k6 tests
        uses: grafana/run-k6-action@c6b79182b9b666aa4f630f4a6be9158ead62536e # v1.2.0
        continue-on-error: false
        env:
          K6_OTEL_METRIC_PREFIX: k6_
          K6_OTEL_GRPC_EXPORTER_INSECURE: true
          # Load test specific environment variables
          BILLING_RELAY_URL: ${{ env.BILLING_RELAY_ENV_URL }}
          BILLING_PAYPAL_WEBHOOK_KEY: ${{ steps.get-kv-secrets.outputs.billing-paypal-webhook-key }}
        with:
          flags: >-
            --tag test-id=${{ env.TEST_ID }}
            -o experimental-opentelemetry
            ${{ inputs.k6-flags }}
          path: ${{ env.K6_TEST_PATH }}
